let numero1;
let numero2;
console.log("ingrese un numero");
console.log("gracias");
numero1 = prompt();
numero2 = prompt();
let suma = parseInt(numero1) + parseInt(numero2);
let resta = numero1 - numero2;
let multiplicacion = numero1 * numero2;
let division = numero1 / numero2;
console.log("la suma de " + numero1 + " y " + numero2 + " es: " + suma );
console.log("la resta de " + numero1 + " y " + numero2 + " es: " + resta );
console.log("la multiplicacion de " + numero1 + " y " + numero2 + " es: " + multiplicacion );
console.log("la division de " + numero1 + " y " + numero2 + " es: " + division );